version: '2.3'

services:
  tuxpay:
    restart: always
    container_name: tuxpay-server
    build:
      context: ""
      dockerfile: Dockerfile
    image: tuxpay:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data:/tuxpay/data
    entrypoint:
      - python3
      - server.py
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"